name: Update dependencies

on:
  push:
    branches:
      - "trunk"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          ref: "trunk"
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install NCU
        run: npm i --save -g npm i npm-check-updates
      - name: Run NCU
        run: ncu -u
      - name: Commit and Push new package-lock.json and package.json to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "trunk"
